# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IOSWithRNDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for IOSWithRNDemo

  pod 'React', :path => ‘./RN/node_modules/react-native', :subspecs => [
  'Core’,
  ‘CxxBridge’,
  ’RCTText',
  ]
  pod ‘yoga', :path => ‘./RN/node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => ‘./RN/node_modules/react-native/third-party-podspecs/Folly.podspec'

end
